spring:
  # 线程池配置
  task:
    execution:
      pool:
        core-size: 24
        max-size: 100
  servlet:
    multipart:
      max-file-size: 4MB

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描,多个package用逗号或者分号分隔
  typeAliasesPackage: cn.dataplatform.open.web.store.entity
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      whereStrategy: NOT_EMPTY
      # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 表驼峰转下划线
      table-underline: true
  # 原生配置
  configuration:
    # 驼峰转下划线
    map-underscore-to-camel-case: true
    cache-enabled: true
    local-cache-scope: session

dp:
  password:
    secret-key: ${DP_PASSWORD_SECRET_KEY:0000000000000000}
  auth:
    jwt:
      # 新版本要求密钥长度必须大于 256
      secret-key: ${DP_JWT_SECRET_KEY:0000000000000000000000000000000000000000000000000000000000000000}
      # token失效时间(毫秒单位)
      keep-time: -1 # 废弃,由redis维护
    token:
      keep-time: 3600000
  loki:
    server-url: ${LOKI_SERVER_URL:http://loki:3100}
  prometheus:
    server-url: ${PROMETHEUS_SERVER_URL:http://prometheus:9001}

# 阿里巴巴oss
aliyun:
  oss:
    enable: ${ALIYUN_OSS_ENABLED:false}
    endPoint: ${ALIYUN_OSS_END_POINT:}
    accessKeyId: ${ALIYUN_OSS_ACCESS_KEY_ID:}
    accessKeySecret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:}
    bucketName: ${ALIYUN_OSS_BUCKET_NAME:}
    defaultFolder: ${ALIYUN_OSS_DEFAULT_FOLDER:}