spring:
  datasource:
    dynamic:
      strict: true
      primary: data_platform
      datasource:
        data_platform:
          url: ${MYSQL_URL:jdbc:mysql://mysql:3306/data_platform}
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:}
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            minimum-idle: 20 # 最小空闲连接数
            maximum-pool-size: 50 # 最大连接数
            connection-timeout: 10000 # 连接超时时间
            idle-timeout: 10000 # 空闲连接超时时间
            max-lifetime: 1800000 # 连接最大生命周期
            validation-timeout: 3000 # 连接校验超时时间
            connection-test-query: SELECT 1 # 连接校验查询语句
            connection-init-sql: SELECT 1
            leak-detection-threshold: 5000  # 帮助检测连接泄漏
            keepalive-time: 30000
      aop:
        enabled: true
