name: mysql

services:
  mysql:
    container_name: mysql
    image: registry.cn-beijing.aliyuncs.com/daodao-bot/mysql:9.2.0
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      TZ: Asia/Shanghai
      DATETIME: "2025-01-01T00:00:00"
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    networks:
      - dp
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

networks:
  dp:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mysql
